name: Heroku Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.6'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your actual requirements file

    - name: Heroku Login
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_app_name: personalized-assistant
        heroku_buildpack: heroku/python

    - name: Set folder location
      run: |
        echo "web: gunicorn your_module:app" > Procfile  # Replace with your module and app name
        echo "your-folder-location" > .slugignore  # Replace with your desired folder location, e.g., 'src/', 'app/'

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Procfile .slugignore
        git commit -m "Add Procfile and .slugignore"
        git push